name: BladeX
version: '2.0'
main: com.bladex.BladeX
api-version: '1.21'
authors: [ Yukile ]
description: BladeX

commands:
  kilicvermenu:
    description: Kılıç verme menüsünü açar.
    usage: /kilicvermenu

  unbreakable:
    description: Elde tutulan menü kılıcını kırılmaz yapar/kaldırır.
    permission: bladex.admin

  keskinlikver:
    description: Elde tutulan menü kılıcına Keskinlik büyüsü basar.
    usage: /keskinlikver <seviye>
    permission: bladex.admin

  alevdencehre:
    description: Elde tutulan menü kılıcına Alev Cehresi büyüsü basar.
    usage: /alevdencehre <seviye>
    permission: bladex.admin

permissions:
  bladex.admin:
    default: op
