name: BladeX
version: '1.0'
main: com.bladex.BladeX
api-version: '1.21'
authors: [ Yukile ]

commands:
  kilicvermenu:
    description: Kiliclar menusu
    usage: /kilicvermenu
    permission: bladex.admin
  bladex:
    description: BladeX komutlari
    usage: /bladex <reload>
    permission: bladex.admin
  bladexreload:
    description: Config yeniden yukle
    usage: /bladexreload
    permission: bladex.admin

permissions:
  bladex.admin:
    default: op
