name: BladeX
version: '${version}'
main: com.bladex.BladeX
api-version: '1.21'
description: "Fear Craft ozel kiliclar & iade sistemi"
authors: [ FearCraft ]

commands:
  kilicvermenu:
    description: "Kılıç menüsünü acar (Admin)"
    usage: /kilicvermenu
    permission: bladex.admin
  iade:
    description: "Iade menüsünü acar (Admin)"
    usage: /iade
    permission: bladex.admin
  bladexreload:
    description: "Config'i yeniden yukler"
    usage: /bladexreload
    permission: bladex.admin

permissions:
  bladex.admin:
    description: "BladeX admin komutlarina erisim"
    default: op
